AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Project Emergence: Aetherium OS
  
  Serverless backend for the Aetherium Operating System, facilitating AI vessel interaction and knowledge synthesis.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 512

Resources:
  EmergenceGenkitFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: packages/hello_world/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          GOOGLE_API_KEY: "{{resolve:secretsmanager:EmergenceAIKey}}"
      Events:
        GenkitApi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /ai/{proxy+}
            Method: any

Outputs:
  EmergenceApi:
    Description: API Gateway endpoint URL for Prod stage for Emergence function
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/ai/
  EmergenceGenkitFunction:
    Description: Emergence Genkit Lambda Function ARN
    Value: !GetAtt EmergenceGenkitFunction.Arn
  EmergenceGenkitFunctionIamRole:
    Description: Implicit IAM Role created for Emergence function
    Value: !GetAtt EmergenceGenkitFunctionRole.Arn
